# Generated by Django 3.2.12 on 2022-02-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_quantity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.FloatField()),
                ('quantity_category', models.CharField(max_length=100)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale_Inventories',
        ),
    ]
